# Generated by Django 3.1.7 on 2021-04-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id_chamado', models.AutoField(primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=255)),
                ('texto', models.CharField(max_length=999)),
                ('data_abertura', models.DateField()),
                ('data_fechamento', models.DateField()),
                ('status', models.IntegerField()),
                ('id_equipamento', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('id_tecnico', models.IntegerField()),
                ('id_area_tec', models.IntegerField()),
            ],
            options={
                'db_table': 'chamado',
            },
        ),
    ]
