# Generated by Django 3.1.7 on 2021-04-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=999)),
                ('senha', models.CharField(max_length=255)),
                ('tipo', models.IntegerField(choices=[(1, 'Comum'), (2, 'Tecnico'), (3, 'Admin')])),
                ('token', models.CharField(max_length=255)),
                ('id_centro_custo', models.IntegerField(choices=[(1, 'Tecnico Roberto'), (2, 'Tecnico Paulo')])),
                ('id_area_tec', models.IntegerField(choices=[(1, 'Administrativo'), (2, 'Financeiro'), (3, 'TI'), (4, 'Almox')])),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id_area_tec',
            field=models.IntegerField(choices=[(1, 'Administrativo'), (2, 'Financeiro'), (3, 'TI'), (4, 'Almox')]),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id_equipamento',
            field=models.IntegerField(choices=[(1, 'Computador'), (2, 'Servidor'), (3, 'Telefone')]),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id_tecnico',
            field=models.IntegerField(choices=[(1, 'Tecnico Roberto'), (2, 'Tecnico Paulo')]),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aberto'), (2, 'Em processamento'), (3, 'Cancelado'), (4, 'Concluido')]),
        ),
    ]
