# Generated by Django 3.1.7 on 2021-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210403_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='assunto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_fechamento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id_area_tec',
            field=models.IntegerField(choices=[(1, 'Administrativo'), (2, 'Financeiro'), (3, 'TI'), (4, 'Almox')], null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id_equipamento',
            field=models.IntegerField(choices=[(1, 'Computador'), (2, 'Servidor'), (3, 'Telefone')], null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id_tecnico',
            field=models.IntegerField(choices=[(1, 'Tecnico Roberto'), (2, 'Tecnico Paulo')], null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id_usuario',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aberto'), (2, 'Em processamento'), (3, 'Cancelado'), (4, 'Concluido')], null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='texto',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
