# Generated by Django 3.1.7 on 2021-04-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210403_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Tecnica',
            fields=[
                ('id_area_tec', models.AutoField(primary_key=True, serialize=False)),
                ('area_tec', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'area_tecnica',
            },
        ),
        migrations.AlterField(
            model_name='chamado',
            name='id_area_tec',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_area_tec',
            field=models.IntegerField(),
        ),
    ]
