# Generated by Django 3.2 on 2021-04-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210403_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('patrimonio', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=999)),
            ],
            options={
                'db_table': 'equipamento',
            },
        ),
    ]
