# Generated by Django 3.2 on 2021-04-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210403_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Tecnica',
            fields=[
                ('id_area_tec', models.AutoField(primary_key=True, serialize=False)),
                ('area_tec', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'area_tecnica',
            },
        ),
    ]
