# Generated by Django 3.1.7 on 2021-04-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210430_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('patrimonio', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=999)),
            ],
            options={
                'db_table': 'equipamento',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('id_usuario', models.IntegerField(null=True)),
                ('id_area_tec', models.IntegerField()),
            ],
            options={
                'db_table': 'tecnico',
            },
        ),
    ]
