# Generated by Django 3.1.7 on 2021-05-01 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210430_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
